[package]
name = "arbo-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.4.0"
ark-ff = "0.4.2"
ark-std = "0.4.0"
poseidon-ark = { git = "https://github.com/arnaucube/poseidon-ark" }
num-bigint = "0.4.6"
num-traits = "0.2.19"
