[package]
name = "arbo-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4.6", features = ["serde"] }
num-traits = "0.2.19"
sp1-zkvm = "2.0.0"
blake3 = "1.5.4"
smtverifier = { path = "../lib" }
